<a href="https://colab.research.google.com/github/alex-degarate/DAnalytics/blob/main/preproyecto/fechas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from datetime import datetime
url2 =""

In [49]:
df_fechas = pd.read_csv( url2 + "fechas2.csv", index_col=0)

In [50]:
df_fechas.info()

df_fechas.head()

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 0 to 89
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fecha_ini  90 non-null     object
dtypes: object(1)
memory usage: 1.4+ KB

    fecha_ini
0  2024-10-22
1  2024-03-20
2  2024-04-13
3  2024-03-31
4  2024-11-27

## convierto un campo de fecha texto ISO a dataframe formato british

In [51]:

df_fechas["fecha_ini"] = pd.to_datetime(df_fechas["fecha_ini"]).dt.strftime("%d/%m/%Y")

In [52]:
df_fechas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 0 to 89
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fecha_ini  90 non-null     object
dtypes: object(1)
memory usage: 3.5+ KB

In [53]:
df_fechas.head()

    fecha_ini
0  22/10/2024
1  20/03/2024
2  13/04/2024
3  31/03/2024
4  27/11/2024

In [47]:
#df_fechas["fecha_new"] = pd.to_datetime(df_fechas["fecha_ini"]).dt.strftime("%d/%m/%Y")