<a href="https://colab.research.google.com/github/alex-degarate/DAnalytics/blob/main/After_12/Greg/plotly_tutorial_greg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
url = "https://github.com/alex-degarate/DAnalytics/raw/refs/heads/main/After_13/Greg/"

# el archivo original no esta delimitado por comas
df = pd.read_csv( url + "AnnualTicketSales.csv")
df.head()

,YEAR,TICKETS_SOLD,TOTAL_BOX_OFFICE,TOTAL_INFLATION_ADJUSTED_BOX_OFFICE,AVERAGE_TICKET_PRICE
0,2021,"42,37,74,881","$3,881,777,912","$3,881,777,912",$9.16
1,2020,"22,36,38,958","$2,048,534,616","$2,048,534,616",$9.16
2,2019,"1,22,85,41,629","$11,253,443,955","$11,253,444,050",$9.16
3,2018,"1,31,15,36,128","$11,948,096,650","$12,013,670,952",$9.11
4,2017,"1,22,56,39,761","$10,993,991,460","$11,226,860,216",$8.97

In [ ]:
# el csv presenta varios problemas:
#  los campos no estan separados por comas
#  el nombre de los campos contienen espacios
# varios campos contienen ',' y '$'

#df.drop(df.columns[-1], axis=1, inplace=True)
#df.drop('TOTAL_INFLATION_ADJUSTED_BOX_OFFICE', axis=1, inplace=True)

def fix_columns(x):
  x = str(x)
  x = x.replace(',', '')
  x = x.replace('$', '')

  return int(float(x))

for column in df.columns:
  df[column] = df[column].apply(fix_columns)

df.head()

,YEAR,TICKETS_SOLD,TOTAL_BOX_OFFICE,TOTAL_INFLATION_ADJUSTED_BOX_OFFICE,AVERAGE_TICKET_PRICE
0,2021,423774881,3881777912,3881777912,9
1,2020,223638958,2048534616,2048534616,9
2,2019,1228541629,11253443955,11253444050,9
3,2018,1311536128,11948096650,12013670952,9
4,2017,1225639761,10993991460,11226860216,8

In [ ]:
len(df)

27

In [ ]:
#!pip install plotly --upgrade

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Collecting plotly
  Downloading plotly-6.5.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from plotly) (2.13.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (25.0)
Downloading plotly-6.5.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 79.9 MB/s eta 0:00:00
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1
Successfully installed plotly-6.5.0

In [ ]:
import plotly.express as px

px.pie(df,
       names='AVERAGE_TICKET_PRICE')

In [ ]:
px.histogram(df, x='TICKETS_SOLD', nbins=2, title='Histogram of Tickets Sold')

In [ ]:
fig = px.box(df,
       y='TOTAL_BOX_OFFICE',
       title='Box & Whisker Plot of Total Box Office',
       hover_data=['YEAR'],
       )
fig.update_traces(fillcolor='#ffffcc', line=dict(color='navy', width=2))

fig.show()

In [ ]:
fig = px.scatter(df, x='YEAR',
           y='TICKETS_SOLD',
           title='Movie Ticket Sales vs Time')

fig.update_traces(marker=dict(size=16,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [ ]:
px.bar(df, x='YEAR', y='TOTAL_BOX_OFFICE', color='AVERAGE_TICKET_PRICE')

In [ ]:
fig = px.scatter(df, x='YEAR',
           y='TICKETS_SOLD',
           size='AVERAGE_TICKET_PRICE',
           title='Movie Ticket Sales vs Time',
           labels={'TICKETS_SOLD':'Tickets Sold',
                   'YEAR':'Year'}
           )

fig.update_traces(marker=dict(
            color='Green',
              line=dict(
              color='Blue',
            width=2
            )
        ),)

fig.update_layout(
    font_family="Calibri",
    font_color="blue",
    font_size=18,
    title_font_family="Bangers",
    title_font_size=48,
    title_font_color="Red",
)

fig.show()

In [ ]:
import numpy as np

x, y = np.arange(10), np.arange(10, 20)

px.scatter(x=x, y=y)

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()

x = np.arange(-30, 30)

fig.add_trace(go.Scatter(x=x, y=x**1, mode='markers', name='Linear'))

fig.add_trace(go.Scatter(x=x, y=x**2, mode='markers', name='Quadratic'))

fig.update_layout(title="Linear vs Quadratic Functions!")

fig.show()

In [ ]:
from plotly.subplots import make_subplots

fig = make_subplots(rows=2, cols=2,
                    subplot_titles=("Linear", "Square", "Cube", "Quarted"))

x = np.arange(-30, 30)

fig.add_trace(go.Scatter(x=x, y=x**1, mode='markers'),
              row=1, col=1)

fig.add_trace(go.Scatter(x=x, y=x**2, mode='markers'),
              row=1, col=2)

fig.add_trace(go.Scatter(x=x, y=x**3, mode='markers'),
              row=2, col=1)

fig.add_trace(go.Scatter(x=x, y=x**4, mode='markers'),
              row=2, col=2)

fig.update_layout(showlegend=False, title="What Nice Graphs!")


fig.show()